name: pre-commit-check
on: [push, pull_request]
jobs:
  check-something:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - run: |
          echo $(git diff --name-only --diff-filter=AM ${{ github.event.before }} ${{ github.sha }})
      - run: |
          echo $(git diff-index HEAD --cached)
      - run: |
          echo $(git diff-index HEAD)
      - name: Branch name 1
        run: echo "branch $GITHUB_REF sha $GITHUB_SHA repo $GITHUB_REPOSITORY actor $GITHUB_ACTOR"
      - name: Branch name 2
        run: echo running on branch ${GITHUB_HEAD_REF##*/}
      - name: Branch name 3
        run: echo running on branch ${GITHUB_BASE_REF##*/}
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
      - run: |
          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
          for added_modified_file in "${added_modified_files[@]}"; do
            echo "Do something with this ${added_modified_file}."
            main/githooks.py ${add_modified_file}
          done
