name: pre-commit-check
on: [push]
jobs:
  check-something:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julianwachholz/flake8-action@v1.1.0
	    with:
		  checkName: flake8
		  path: main
