name: pre-commit-check
on: [push, pull_request]
jobs:
  check-something:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install flake8
        run: pip install flake8
        #      - name: Run flake8
        #        run: flake8 main && exit 0
      - name: Run git
        run: git diff-index HEAD --cached
